AWSTemplateFormatVersion: 2010-09-09
Description: Create Sagemaker Endpoint
Parameters:
  endpointconfigname:
    Type: String
    Description: Endpoint COnfig Name
  costCenterValue:
    Type: String
    Description: COSTCENTER tag value
  stackNameValue:
    Type: String
    Description: STACKNAME tag value
Resources:
  sagemakerendpoint:
    Type: AWS::SageMaker::Endpoint
    Properties:
      EndpointConfigName: !Ref endpointconfigname
      Tags:
      - Key: COSTCENTER
        Value: !Ref costCenterValue
      - Key: STACKNAME
        Value: !Ref stackNameValue
