AWSTemplateFormatVersion: 2010-09-09
Description: Create ECS CLuster
Parameters:
  costCenterValue:
    Type: String
    Description: COSTCENTER tag value
  stackNameValue:
    Type: String
    Description: STACK tag value
Resources:
  awsecscluster:
    Type: AWS::ECS::Cluster
    Properties:
        Tags:
        - Key: COSTCENTER
          Value: !Ref costCenterValue
        - Key: STACK
          Value: !Ref stackNameValue
