AWSTemplateFormatVersion: 2010-09-09
Description: Create API Gateway Usages Plan
Parameters:
  costCenterValue:
    Type: String
    Description: COSTCENTER tag value
  stackNameValue:
    Type: String
    Description: STACKNAME tag value
Resources:
  awsapigwusagesplan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
        Tags:
        - Key: COSTCENTER
          Value: !Ref costCenterValue
        - Key: STACKNAME
          Value: !Ref stackNameValue