AWSTemplateFormatVersion: 2010-09-09
Description: Create SQS Queue
Parameters:
  costCenterValue:
    Type: String
    Description: COSTCENTER tag value
  stackNameValue:
    Type: String
    Description: STACKNAME tag value
Resources:
  sqspolicy:
    Type: AWS::SQS::Queue
    Properties:
      Tags:
      - Key: COSTCENTER
        Value: !Ref costCenterValue
      - Key: STACKNAME
        Value: !Ref stackNameValue