AWSTemplateFormatVersion: 2010-09-09
Description: Create ECS Service
Parameters:
  costCenterValue:
    Type: String
    Description: COSTCENTER tag value
  stackNameValue:
    Type: String
    Description: STACKNAME tag value
Resources:
  awsecsservice:
    Type: AWS::ECS::Service
    Properties:
        Tags:
        - Key: COSTCENTER
          Value: !Ref costCenterValue
        - Key: STACKNAME
          Value: !Ref stackNameValue