AWSTemplateFormatVersion: 2010-09-09
Description: Create Sagemaker Model
Parameters:
  executionrolearn:
    Type: String
    Description: Execution Role ARN
  costCenterValue:
    Type: String
    Description: COSTCENTER tag value
  stackNameValue:
    Type: String
    Description: STACKNAME tag value
Resources:
  sagemakermodel:
    Type: AWS::SageMaker::Model
    Properties:
      ExecutionRoleArn: !Ref executionrolearn
      Tags:
      - Key: COSTCENTER
        Value: !Ref costCenterValue
      - Key: STACKNAME
        Value: !Ref stackNameValue