AWSTemplateFormatVersion: 2010-09-09
Description: Create Pinpoint APNS Channel
Parameters:
  applicationid:
    Type: String
    Description: The unique identifier for the application
Resources:
  pinpointapnschannel:
    Type: AWS::Pinpoint::APNSChannel
    Properties:
      ApplicationId: !Ref applicationid
