AWSTemplateFormatVersion: 2010-09-09
Description: Create Amplify Branch
Parameters:
  appid:
    Type: String
    Description: Amplify App ID  
  branchname:
    Type: String
    Description: Amplify App Branch Name
  costCenterValue:
    Type: String
    Description: COSTCENTER tag value
  stackNameValue:
    Type: String
    Description: STACK tag value
Resources:
  awsamplifyapp:   
    Type: AWS::Amplify::Branch
    Properties: 
      AppId: !Ref appid
      BranchName: !Ref branchname
      Tags:
      - Key: COSTCENTER
        Value: !Ref stack
      - Key: STACK
        Value: !Ref stackNameValue
