AWSTemplateFormatVersion: 2010-09-09
Description: Create RDS DB CLuster
Parameters:
  dbengine:
    Type: String
    Description: The name of the database engine
  costCenterValue:
    Type: String
    Description: COSTCENTER tag value
  stackNameValue:
    Type: String
    Description: STACK tag value
Resources:
  rdsdbcluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: !Ref dbengine
      Tags:
      - Key: COSTCENTER
        Value: !Ref costCenterValue
      - Key: STACK
        Value: !Ref stackNameValue
