AWSTemplateFormatVersion: 2010-09-09
Description: Create DMS Replication Subnet Group
Parameters:
  replicationsubnetgroup:
    Type: String
    Description: Replication Subnet Group Description
  subnetid:
    Type: String
    Description: List of Subnet IDs
  costCenterValue:
    Type: String
    Description: COSTCENTER tag value
  stackNameValue:
    Type: String
    Description: STACKNAME tag value
Resources:
  awsdmsreplicationsubnetgroup:
    Type: AWS::DMS::ReplicationSubnetGroup
    Properties: 
        ReplicationSubnetGroupDescription: !Ref replicationsubnetgroup
        SubnetIds: !Ref subnetid
        Tags:
        - Key: COSTCENTER
          Value: !Ref costCenterValue
        - Key: STACKNAME
          Value: !Ref stackNameValue