AWSTemplateFormatVersion: 2010-09-09
Description: Create S3 Bucket Policy
Parameters:
  bucket:
    Type: String
    Description: Name of bucket
  policydocument:
    Type: String
    Description: Policy Document in Json  
Resources:
  s3bucketpolicy:
    Type: AWS::S3::Bucket
    Properties:
      Bucket: !Ref bucket
      PolicyDocument: !Ref policydocument