AWSTemplateFormatVersion: 2010-09-09
Description: Create Athena Work Group
Parameters:
  name:
    Type: String
    Description: Athena Work Group name
  costCenterValue:
    Type: String
    Description: COSTCENTER tag value
  stackNameValue:
    Type: String
    Description: STACK tag value
Resources:
  awsathenaworkgroup:
    Type: AWS::Athena::WorkGroup
    Properties: 
        Name: !Ref name
        Tags:
        - Key: COSTCENTER
          Value: !Ref costCenterValue
        - Key: STACK
          Value: !Ref stackNameValue
