AWSTemplateFormatVersion: 2010-09-09
Description: Create Pinpoint Push Template
Parameters:
  templatename:
    Type: String
    Description: Template Name
  costCenterValue:
    Type: String
    Description: COSTCENTER tag value
  stackNameValue:
    Type: String
    Description: STACK tag value
Resources:
  pinpointpushtemplate:
    Type: AWS::Pinpoint::PushTemplate
    Properties:
      TemplateName: !Ref templatename
      Tags:
      - Key: COSTCENTER
        Value: !Ref costCenterValue
      - Key: STACK
        Value: !Ref stackNameValue
