AWSTemplateFormatVersion: 2010-09-09
Description: Create S3 Bucket
Parameters:
  costCenterValue:
    Type: String
    Description: COSTCENTER tag value
  stackNameValue:
    Type: String
    Description: STACK tag value
Resources:
  s3bucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
      - Key: COSTCENTER
        Value: 'value;'
      - Key: STACK
        Value: !Ref stackNameValue
