AWSTemplateFormatVersion: 2010-09-09
Description: Create ELB Load Balancer
Parameters:
  name:
    Type: String
    Description: Name of LB
  costCenterValue:
    Type: String
    Description: COSTCENTER tag value
  stackNameValue:
    Type: String
    Description: STACK tag value
Resources:
  elbloadbalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref name
      Tags:
      - Key: COSTCENTER
        Value: !Ref costCenterValue
      - Key: STACK
        Value: !Ref stackNameValue
