AWSTemplateFormatVersion: 2010-09-09
Description: Create Lambda Layer Version
Parameters:
  s3bucket:
    Type: String
    Description: S3 Bucket
  s3key:
    Type: String
    Description: S3 Key
Resources:
  lambdalayerversion:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
      - S3Bucket: !Ref s3bucket
        S3Key: !Ref s3key
