AWSTemplateFormatVersion: 2010-09-09
Description: Create RDS DB Instance
Parameters:
  dbinstanceclass:
    Type: String
    Description: DB Instance Class
  costCenterValue:
    Type: String
    Description: COSTCENTER tag value
  stackNameValue:
    Type: String
    Description: STACKNAME tag value
Resources:
  rdsdbinstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: !Ref dbinstanceclass
      Tags:
      - Key: COSTCENTER
        Value: !Ref costCenterValue
      - Key: STACKNAME
        Value: !Ref stackNameValue