AWSTemplateFormatVersion: 2010-09-09
Description: Create ECR Repository
Parameters:
  costCenterValue:
    Type: String
    Description: COSTCENTER tag value
  stackNameValue:
    Type: String
    Description: STACK tag value
Resources:
  awsecrrepo:
    Type: AWS::ECR::Repository
    Properties:
        Tags:
        - Key: COSTCENTER
          Value: !Ref costCenterValue
        - Key: STACK
          Value: !Ref stackNameValue
