AWSTemplateFormatVersion: 2010-09-09
Description: Create Secret Manager Resource Policy
Parameters:
  resourcepolicy:
    Type: String
    Description: JSON Resource Policy
  secretid:
    Type: String
    Description: Secret ID
Resources:
  secretmanagerresourcepolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      ResourcePolicy: !Ref resourcepolicy
      SecretId: !Ref secretid