AWSTemplateFormatVersion: 2010-09-09
Description: Create SNS Topic
Parameters:
  costCenterValue:
    Type: String
    Description: COSTCENTER tag value
  stackNameValue:
    Type: String
    Description: STACKNAME tag value
Resources:
  snstopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
      - Key: COSTCENTER
        Value: !Ref costCenterValue
      - Key: STACKNAME
        Value: !Ref stackNameValue