AWSTemplateFormatVersion: 2010-09-09
Description: Create ECS TaskDefinition
Parameters:
  costCenterValue:
    Type: String
    Description: COSTCENTER tag value
  stackNameValue:
    Type: String
    Description: STACK tag value
Resources:
  awsecstaskdefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Tags:
      - Key: COSTCENTER
        Value: !Ref costCenterValue
      - Key: STACK
        Value: !Ref stackNameValue
