AWSTemplateFormatVersion: 2010-09-09
Description: Create Amplify APP
Parameters:
  name:
    Type: String
    Description: Amplify App name
  costCenterValue:
    Type: String
    Description: COSTCENTER tag value
  stackNameValue:
    Type: String
    Description: STACK tag value
Resources:
  awsamplifyapp:
    Type: AWS::Amplify::App
    Properties: 
        Name: !Ref name
        Tags:
        - Key: COSTCENTER
          Value: !Ref costCenterValue
        - Key: STACK
          Value: !Ref stackNameValue
          
