AWSTemplateFormatVersion: 2010-09-09
Description: Create Code Build Source Credentials
Parameters:
  authtype:
    Type: String
    Description: Authentication Type
    AllowedValues:
    - BASIC_AUTH 
    - OAUTH 
    - PERSONAL_ACCESS_TOKEN
  servertype:
    Type: String
    Description: Server Type
    AllowedValues:
    - BITBUCKET 
    - GITHUB 
    - GITHUB_ENTERPRISE
  token:
   Type: String
   Description: Token
Resources:
  awscodebuildsourcecredentials:
    Type: AWS::CodeBuild::SourceCredential
    Properties: 
      AuthType: !Ref authtype
      ServerType: !Ref servertype
      Token: !Ref token