AWSTemplateFormatVersion: 2010-09-09
Description: Create Glue Crawler
Parameters:
  Name:
    Type: String
    Description: Name of Work Flow
  databasename:
    Type: String
    Description: Name of DB
  costCenterValue:
    Type: String
    Description: COSTCENTER tag value
  stackNameValue:
    Type: String
    Description: STACKNAME tag value
Resources:
  gluecrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Ref name
      Targets:
      - CatalogTargets:
        - DatabaseName: !Ref databasename
      Tags:
      - Key: COSTCENTER
        Value: !Ref costCenterValue
      - Key: STACKNAME
        Value: !Ref stackNameValue