AWSTemplateFormatVersion: 2010-09-09
Description: Create Secret Manager Secret
Parameters:
  name:
    Type: String
    Description: Name of Secret
  costCenterValue:
    Type: String
    Description: COSTCENTER tag value
  stackNameValue:
    Type: String
    Description: STACK tag value
Resources:
  secretmanagersecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref name
      Tags:
      - Key: COSTCENTER
        Value: !Ref costCenterValue
      - Key: STACK
        Value: !Ref stackNameValue
