AWSTemplateFormatVersion: 2010-09-09
Description: Create Secret Manager Rotation Schedule
Parameters:
  secretid:
    Type: String
    Description: Secret ID
Resources:
  secretmanagerrotationschedule:
    Type: AWS::SecretsManager::RotationSchedule
    Properties:
      SecretId: !Ref secretid
