AWSTemplateFormatVersion: 2010-09-09
Description: Create Secret Manager Secret Target Attachment
Parameters:
  targetid:
    Type: String
    Description: The ARN of the service or database credentials stored in the specified secret
  secretid:
    Type: String
    Description: ARN or friendly name of secret
  targettype:
    Type: String
    Description: A string that defines the type of service or database associated with the secret
Resources:
  secretmanagersecrettargetattachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      TargetId: !Ref targetid
      SecretId: !Ref secretid
      TargetType: !Ref targettype
