AWSTemplateFormatVersion: 2010-09-09
Description: Create API Gateway Request Validator
Parameters:
  name:
    Type: String
    Description: Model Name
  restapiid:
    Type: String
    Description: Rest API ID
Resources:
  awsapigwrequestvalidator:
    Type: AWS::ApiGateway::Model
    Properties:
      Name: !Ref name
      RestApiId: !Ref restapiid
