AWSTemplateFormatVersion: 2010-09-09
Description: Create API Gateway CLient Certificate
Parameters:
  costCenterValue:
    Type: String
    Description: COSTCENTER tag value
  stackNameValue:
    Type: String
    Description: STACKNAME tag value
Resources:
  awsapigwclientcertificate:
    Type: AWS::ApiGateway::ClientCertificate
    Properties:
      Tags:
        - Key: COSTCENTER
          Value: !Ref costCenterValue
        - Key: STACKNAME
          Value: !Ref stackNameValue